```{r setup}
library(gt)
library(gtExtras)
library(dplyr, warn.conflicts =  FALSE)
library(ggplot2)
library(magrittr)
library(purrr)
library(ggpubr)
library(dplyr)
library(tidyr)
library(tidyverse)
library(ggridges)
library(ggrepel)
library(data.table)
```

The following code then imports the data from Gary, then calculate points difference and total points scored

```{r conferencetables}
league_dat <- data.frame(read.csv('round8.csv'))
# calculate points difference, total points and bonus points
league_dat$Pts.Diff <- league_dat$Points.Scored - league_dat$Points.Conceded
league_dat$Bonus.Points <- league_dat$Bonus.Points..Losing. +
                           league_dat$Bonus.Points..Try.
league_dat <- select(league_dat, -Bonus.Points..Losing., 
                                 -Bonus.Points..Try.) # remove excess
league_dat$Points <- league_dat$Wins*4 +
                     league_dat$Draws*2 + 
                     league_dat$Bonus.Points
# create extra collumns for data plots
league_dat$ConcededPlt <- league_dat$Points.Conceded
league_dat$ScoredPlt <- league_dat$Points.Scored

# create form variable and then add into the table
form <- list(c(0,1,0,1,1,0,1,0), # Sam
             c(1,1,1,1,1,1,1,1), # Ben
             c(1,0,0,1,1,1,0,0), # Rhu
             c(0,0,1,0,0,0,0,1), # Cheese
             c(0,1,1,0,0,1,1,1), # Steggles
             c(1,0,0,0,0,0,0,0), # Jamie
             c(1,0,0,1,0,1,0,0), # Dan
             c(1,1,0,1,1,1,1,0), # Alex
             c(0,0,1,1,1,0,1,1), # Jack
             c(0,1,0,0,1,0,0,0), # Gary
             c(0,1,1,0,0,0,0,1), # Oli
             c(1,0,1,0,0,1,1,0)  # Luke
             )
league_dat$Form <- form

# create previous position variable and then add into the table
pastpos <- list(c(3), # Sam
             c(1), # Ben
             c(2), # Rhu
             c(5), # Cheese
             c(4), # Steggles
             c(6), # Jamie
             c(2), # Dan
             c(1), # Alex
             c(4), # Jack
             c(5), # Gary
             c(6), # Oli
             c(3)  # Luke
             )
league_dat$Previous.Position <- pastpos

# create the gt table by passing the DF into it
table <- league_dat %>%
  # group by conference
  group_by(league_dat$Conf) %>%
  # decide on the ranking order of priority
  arrange(league_dat$Conf, 
          -league_dat$Points, 
          -league_dat$Pts.Diff,
          league_dat$Team.Name) %>%
  # add in the rank collumn
  mutate(Rank = 1:n())

  table$PosChng <- as.numeric(unlist(table$Previous.Position)) - table$Rank
  
  table <- select(table, -Previous.Position) %>%
  # create as gt
    gt() %>%
  # create win-loss plot in place of the form variable and move to after the loss collumn
  gt_plt_winloss(Form,
                 palette = c("blue",
                             "red",
                             "black")) %>%
  cols_move(
    columns = Form,
    after = Losses) %>%
  # add divider after form
  gt_add_divider(columns = Form, 
                 color = "grey", 
                 style = "solid") %>%
  # plot the difference plot and move if necessary
  gt_plt_bar(column = Pts.Diff, 
             keep_column = FALSE, 
             width = 35,
             color = "darkgrey",
             scale_type = "number") %>%
  # plot the scored plot and move if necessary
  gt_plt_bar_pct(column = ScoredPlt, 
                    scaled = FALSE, 
                    fill = "blue", 
                    background = "lightblue") %>%
  cols_move(
    columns = ScoredPlt,
    after = Points.Scored) %>%
  # plot the scored plot and move if necessary
  gt_plt_bar_pct(column = ConcededPlt, 
                    scaled = FALSE, 
                    fill = "red", 
                    background = "pink") %>%
  cols_move(
    columns = ConcededPlt,
    after = Points.Conceded) %>%
  # swap plot and number for the points sections
  cols_move(
    columns = Points.Conceded,
    after = ConcededPlt) %>%
  cols_move(
    columns = Points.Scored,
    after = ScoredPlt) %>%
  gt_add_divider(columns = Pts.Diff, 
                 color = "grey", 
                 style = "solid") %>%
  # move rank and team to the very start and divide from rest
  cols_move_to_start(columns = c(Rank, 
                                 Team.Name)) %>%
  # add divider after team
  gt_add_divider(columns = Team.Name, 
                 color = "grey", 
                 style = "solid") %>%
  # add in ID column and then swap ID to picture
  cols_move(
    columns = ID,
    after = Rank) %>%
  fmt_image(
    columns = ID,
    path = "./imgs/",
    file_pattern = "avatar_{x}.png") %>%
  # hide conference collumn now as already grouped
  cols_hide(columns = c(Conf)) %>%
  # label collumns appropriately
  cols_label(
    ID = md(" "),
    Player = md("**PLAYER**"),
    Team.Name = md("**TEAM**"),
    Conf = md("**CONFERENCE**"),
    Wins = md("**W**"),
    Draws = md("**D**"),
    Losses = md("**L**"),
    Bonus.Points = md("**BP**"),
    ScoredPlt = md("**SCORED**"),
    ConcededPlt = md("**CONCEDED**"),
    Points = md("**PTS**"),
    Rank = md("**RANK**"),
    Form = md("**FORM**"),
    Pts.Diff = md("**DIFFERENCE**"),
    Points.Scored = md(" "),
    Points.Conceded = md(" "),
    PosChng = md("**CHANGE**")
  ) %>%
  # colour in the rows according to whether championship qualifier or not
  tab_style(
    style = list(
      cell_fill(color = "red", alpha = 0.1),
      cell_text(color = "black")
      ),
    locations = cells_body(rows = Rank > 4)) %>%
  # as
  tab_style(
    style = list(
      cell_fill(color = "green", 
                alpha = 0.1),
      cell_text(color = "black")),
    locations = cells_body(rows = Rank < 5)) %>%
  # add in footnotes
  tab_footnote(
    footnote = "1 win = 4 points",
    locations = cells_column_labels(columns = Wins)) %>%
  tab_footnote(
    footnote = "1 draw = 2 points",
    locations = cells_column_labels(columns = Draws)) %>%
  tab_footnote(
    footnote = "1 bonus point for scoring 4 or more tries and/or losing within 7 points",
    locations = cells_column_labels(columns = Bonus.Points)) %>%
  tab_footnote(
    footnote = "Positions based on points scored, points difference, scored and then conceded in that order",
    locations = cells_column_labels(columns = Rank)) %>%
  # housekeeping
  cols_align(align = ("left"),
             columns = everything()) %>%
  gt_merge_stack(col1 = Team.Name, 
                 col2 = Player) %>%
    text_transform(
    locations = cells_body(columns = vars(PosChng)),
    fn = function(x){
      
      PosChng <- as.integer(x)
      
      choose_logo <-function(x){
        if (x == 0){
        gt::html(fontawesome::fa("equals", fill = "grey"))
      } else if (x > 0){
         gt::html(glue::glue("<span style='color:#028AOF;font-face:bold;font-size:14px;'>{x}</span>"), fontawesome::fa("arrow-up", fill = "#1134A6"))
      } else if (x < 0) {
        gt::html(glue::glue("<span style='color:#DA2A2A;font-face:bold;font-size:14px;'>{x}</span>"), fontawesome::fa("arrow-down", fill = "#DA2A2A"))
      }
      } 
      
      map(PosChng, choose_logo)
    
    }
  ) %>%
    cols_move(
      columns = PosChng,
      after = Rank) %>%
    gtsave("leaguetable.png", expand = 20)
    
# call the table
table

```

```{r pdtab}

ggdotchart(league_dat, x = "Player", y = "Pts.Diff",
           color = "Conf",                               # Color by groups
           palette = c("#00AFBB", "#E7B800", "#FC4E07"), # Custom color palette
           sorting = "descending",                       # Sort value in descending order
           add = "segments",                             # Add segments from y = 0 to dots
           add.params = list(color = "lightgray", size = 2), # Change segment color and size
           group = "Pts.Diff",                                # Order by groups
           dot.size = 10,                                 # Large dot size
           label = round(league_dat$Pts.Diff,1),         # Add mpg values as dot labels
           font.label = list(color = "white", size = 9, 
                             vjust = 0.5),               # Adjust label parameters
           ggtheme = theme_pubr()                        # ggplot2 theme
           )+
  geom_hline(yintercept = 0, linetype = 2, color = "lightgray") + 
  labs(x = "Player") +
  labs(y = "Points Difference") + 
  labs(color = "Conference") + rotate_x_text(45) +
  theme(axis.title=element_text(face="bold"))

ggsave("DifferenceTab.png")
```

```{r scores}
wklyScored <- data.frame(read.csv('WeeklyPoints.csv'))

wklyScored[wklyScored == 0] <- NA

pal <- colorRampPalette(c("red","green"))

ridgeline <- wklyScored %>%
    pivot_longer(!Team, names_to = "Round", values_to = "Scored") %>% 
    na.omit() %>%
    ggplot(., aes(x = Scored, 
                  y = fct_reorder(Team, 
                                  Scored, 
                                  .fun = sum),
                  fill = Team)) +
  geom_density_ridges() + 
    theme_classic() + theme(legend.position = "none") +
    labs(x = "Points Scored") +
    labs(y = " ") + scale_fill_manual(values = alpha(pal(12), .95)) +
  theme(axis.title=element_text(face="bold"))

ggsave("ScoringDensity.png")
```
```{r cumulativepoints}

# prepare data
dat <- wklyScored %>%
    pivot_longer(!Team, 
                 names_to = "Round", 
                 values_to = "Scored") %>% 
    group_by(Team) %>%
    mutate(cv=cumsum(Scored)) %>%
    mutate(r = 1:15)

ggplot(dat, 
       aes(x = r, 
           y = cv, 
           colour = Team,
           group = Team)) + 
  geom_line(size = 0.5, alpha = 0.8)+
  geom_point(size = 1, alpha = 0.8) + theme_classic() + 
  labs(y = "Cumulative Points Scored") +
  labs(x = "Round #") + 
  scale_x_continuous(breaks = 1:15) +
  ylim(0,(max(na.omit(dat$cv)))*1.2) +
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"))

ggsave("CumulativeScoring.png")
```

```{r quadrant}
ggplot(league_dat, 
       aes(x = Points.Scored, y = Points.Conceded)) +
  geom_hline(yintercept=mean(league_dat$Points.Conceded),
             linetype="dashed", color = "black") +
  geom_vline(xintercept=mean(league_dat$Points.Scored),
             linetype="dashed", color = "black") +
  annotate("text", 
           x = mean(league_dat$Points.Scored)-55, 
           y = mean(league_dat$Points.Conceded)-45, 
           label = ("Missed Chances"), 
           fontface = 2, alpha = 0.5) +
  annotate("text", 
           x = mean(league_dat$Points.Scored)-55, 
           y = mean(league_dat$Points.Conceded)+55, 
           label = ("Deserved Defeats"), 
           fontface = 2, alpha = 0.5) +
  annotate("text", 
           x = mean(league_dat$Points.Scored)+55, 
           y = mean(league_dat$Points.Conceded)+55, 
           label = ("Tough Matchups"), 
           fontface = 2, alpha = 0.5) +
  annotate("text", 
           x = mean(league_dat$Points.Scored)+55, 
           y = mean(league_dat$Points.Conceded)-45, 
           label = ("Deserved Wins"), 
           fontface = 2, alpha = 0.5) +
  geom_point(color = "blue", size = 3) +
  geom_label_repel(aes(label = Player),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50') +
  theme_classic() + 
  labs(x = "Average Points Scored") +
  labs(y = "Average Points Conceded") +
  theme(axis.title=element_text(face="bold"))

ggsave("QuadrantPlot.png")
```
```{r historicalpos}
histpos <- data.frame(read.csv('roundhistory.csv'))
histpos[histpos == 0] <- NA

# prepare the data
dat <- histpos %>%
    pivot_longer(!Team, 
                 names_to = "Round", 
                 values_to = "Points") %>% 
    group_by(Team) %>%
    mutate(r = 1:15) %>%
    na.omit()

ggplot(dat,
       aes(x = r,
           y = Points,
           group = Team)) + 
  geom_line(aes(color = Team), 
            size = 2,
            alpha = 0.6) +
  geom_point(data = dat[dat$r == max(dat$r),],
             aes(x = r, y = Points, 
                 color = Team),
             size = 3) +
  scale_x_continuous(breaks = 1:15) + theme_classic() + 
  geom_label_repel(
    data = dat %>% 
      group_by(Team) %>% 
      filter(r == max(r)), 
    aes(r, Points, fill = Team, label = Team),
    color = "black",
    fill = "white") + theme(legend.position = "none") + 
  labs(x = "Round #") +
  theme(axis.title=element_text(face="bold"))

ggsave("HistoricalPositions.png")


```

``` {r tries}
# weekly tries
weeklytries <- data.frame(read.csv('weeklytries.csv'))
weeklytries[weeklytries == 0] <- NA

# prepare the data
dat <- weeklytries %>%
    pivot_longer(!Team, 
                 names_to = "Round", 
                 values_to = "Tries") %>% 
    group_by(Team) %>%
    mutate(r = 1:15) %>%
    na.omit()

ggplot(dat,
       aes(x = r,
           y = Tries,
           group = Team)) + 
  geom_line(aes(color = Team), 
            size = 2,
            alpha = 0.6) +
  geom_point(data = dat[dat$r == max(dat$r),],
             aes(x = r, y = Tries, 
                 color = Team),
             size = 3) +
  scale_x_continuous(breaks = 1:15) + theme_classic() + 
  geom_label_repel(
    data = dat %>% 
      group_by(Team) %>% 
      filter(r == max(r)), 
    aes(r, Tries, fill = Team, label = Team),
    color = "black",
    fill = "white") + theme(legend.position = "none") + 
  labs(x = "Round #") +
  theme(axis.title=element_text(face="bold"))

ggsave("WeeklyTries.png")


# average tries per match
avetries <- data.frame(read.csv('triesScored.csv'))
avetries[avetries == 0] <- NA
avetries[avetries < 0] <- NA

# prepare the data
dat <- avetries %>%
    pivot_longer(!Team, 
                 names_to = "Round", 
                 values_to = "Tries") %>% 
    group_by(Team) %>%
    mutate(r = 1:15) %>%
    na.omit()

ggplot(dat,
       aes(x = Team,
           y = Tries)) + 
  geom_jitter(aes(colour = Team),
              width = 0.2, 
              size = 2,
              alpha = 0.7,
              show.legend = FALSE) + 
  geom_boxplot(aes(fill = Team),
               outlier.size = 0,
               alpha = 0.4,
               show.legend = FALSE) + theme_classic() + 
  scale_y_continuous(expand = c(0, 0), 
                     limits = c(0, NA)) + 
  geom_hline(yintercept = mean(dat$Tries),
             linetype="dashed") + 
  theme(axis.title=element_text(face="bold"))

ggsave("averageTries.png")
```

```{r recentAverage}
# average points scored over the last 3 games

# average points scored all season
# weekly tries
weeklypts <- data.frame(read.csv('weeklyPoints.csv'))
weeklypts[weeklypts == 0] <- NA

# prepare the data
dat <- weeklypts %>%
    pivot_longer(!Team, 
                 names_to = "Round", 
                 values_to = "Points") %>% 
    group_by(Team) %>%
    mutate(r = 1:15) %>%
    na.omit()

plot <- ggplot(dat,
       aes(x = Team,
           y = Points)) + 
  stat_summary(aes(colour = Team),
               fun.data = "mean_cl_boot", 
               linewidth = 2, 
               size = 3,
               alpha = 0.9, 
               show.legend = FALSE) + 
  geom_point(data = dat[dat$r == max(dat$r),],
             aes(x = Team, 
                 y = Points, 
                 fill = Team),
             size = 8, shape = 21, color = "black", alpha = 0.4,
             show.legend = FALSE) +
  geom_point(data = dat[dat$r == max(dat$r)-1,],
             aes(x = Team, 
                 y = Points, 
                 fill = Team),
             size = 5, shape = 21, color = "black", alpha = 0.4,
             show.legend = FALSE) +
  scale_y_continuous(expand = c(0, 0), 
                     limits = c(75, 250)) + 
  geom_hline(yintercept = mean(dat$Points),
             linetype="dashed") + 
  theme_classic() + 
  theme(axis.title=element_text(face="bold")) 

ggsave("averagePoints.png")
```
